# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('congressesList', '0002_auto_20160308_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congress',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
